// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkData.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_NetworkData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_NetworkData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_NetworkData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_NetworkData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_NetworkData_2eproto;
namespace NetworkData {
class NetworkData;
struct NetworkDataDefaultTypeInternal;
extern NetworkDataDefaultTypeInternal _NetworkData_default_instance_;
}  // namespace NetworkData
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NetworkData {
enum ENetworkType : int {
  LOGIN = 0,
  REGISTER = 1,
  RETRIEVE = 2,
  ACCESS = 3,
  REJECT = 4,
  LOGOUT = 5,
  COUNT_FOR_USER_DATA = 6,
  MOVE = 100,
  ATTACK = 101,
  DROP_ITEM = 102,
  USE_ITEM = 103,
  USE_SKILL = 104,
  COUNT_FOR_LOGIC_DATA = 105,
  SYSTEM_OPTION_1 = 200,
  SYSTEM_OPTION_2 = 201,
  SYSTEM_OPTION_3 = 202,
  COUNT_FOR_SYSTEM_DATA = 203,
  ADMIN_SERVER_OFF = 900,
  ADMIN_SERVER_ON = 901,
  ADMIN_SERVER_REBOOT = 902,
  COUNT_FOR_ADMIN_DATA = 903,
  ENetworkType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ENetworkType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ENetworkType_IsValid(int value);
extern const uint32_t ENetworkType_internal_data_[];
constexpr ENetworkType ENetworkType_MIN = static_cast<ENetworkType>(0);
constexpr ENetworkType ENetworkType_MAX = static_cast<ENetworkType>(903);
constexpr int ENetworkType_ARRAYSIZE = 903 + 1;
const ::google::protobuf::EnumDescriptor*
ENetworkType_descriptor();
template <typename T>
const std::string& ENetworkType_Name(T value) {
  static_assert(std::is_same<T, ENetworkType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENetworkType_Name().");
  return ::google::protobuf::internal::NameOfEnum(ENetworkType_descriptor(), value);
}
inline bool ENetworkType_Parse(absl::string_view name, ENetworkType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENetworkType>(
      ENetworkType_descriptor(), name, value);
}
enum ELoginError : int {
  USER_NOT_FOUND = 0,
  USER_ALREADY_EXIST = 1,
  INCORRECT = 2,
  ELoginError_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ELoginError_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ELoginError_IsValid(int value);
extern const uint32_t ELoginError_internal_data_[];
constexpr ELoginError ELoginError_MIN = static_cast<ELoginError>(0);
constexpr ELoginError ELoginError_MAX = static_cast<ELoginError>(2);
constexpr int ELoginError_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ELoginError_descriptor();
template <typename T>
const std::string& ELoginError_Name(T value) {
  static_assert(std::is_same<T, ELoginError>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ELoginError_Name().");
  return ELoginError_Name(static_cast<ELoginError>(value));
}
template <>
inline const std::string& ELoginError_Name(ELoginError value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ELoginError_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ELoginError_Parse(absl::string_view name, ELoginError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ELoginError>(
      ELoginError_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class NetworkData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetworkData.NetworkData) */ {
 public:
  inline NetworkData() : NetworkData(nullptr) {}
  ~NetworkData() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetworkData(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetworkData(const NetworkData& from) : NetworkData(nullptr, from) {}
  inline NetworkData(NetworkData&& from) noexcept
      : NetworkData(nullptr, std::move(from)) {}
  inline NetworkData& operator=(const NetworkData& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetworkData& operator=(NetworkData&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetworkData& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetworkData* internal_default_instance() {
    return reinterpret_cast<const NetworkData*>(
        &_NetworkData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NetworkData& a, NetworkData& b) { a.Swap(&b); }
  inline void Swap(NetworkData* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetworkData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetworkData* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<NetworkData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetworkData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetworkData& from) { NetworkData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NetworkData* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetworkData.NetworkData"; }

 protected:
  explicit NetworkData(::google::protobuf::Arena* arena);
  NetworkData(::google::protobuf::Arena* arena, const NetworkData& from);
  NetworkData(::google::protobuf::Arena* arena, NetworkData&& from) noexcept
      : NetworkData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpFieldNumber = 1,
    kUuidFieldNumber = 2,
    kDataFieldNumber = 5,
    kTimestampFieldNumber = 6,
    kBufSizeFieldNumber = 4,
    kTypeFieldNumber = 3,
  };
  // string ip = 1;
  void clear_ip() ;
  const std::string& ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* value);

  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(
      const std::string& value);
  std::string* _internal_mutable_ip();

  public:
  // string uuid = 2;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // string data = 5;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .google.protobuf.Timestamp timestamp = 6;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* _internal_mutable_timestamp();

  public:
  // uint64 bufSize = 4;
  void clear_bufsize() ;
  ::uint64_t bufsize() const;
  void set_bufsize(::uint64_t value);

  private:
  ::uint64_t _internal_bufsize() const;
  void _internal_set_bufsize(::uint64_t value);

  public:
  // .NetworkData.ENetworkType type = 3;
  void clear_type() ;
  ::NetworkData::ENetworkType type() const;
  void set_type(::NetworkData::ENetworkType value);

  private:
  ::NetworkData::ENetworkType _internal_type() const;
  void _internal_set_type(::NetworkData::ENetworkType value);

  public:
  // @@protoc_insertion_point(class_scope:NetworkData.NetworkData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 1,
      42, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetworkData_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetworkData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::Timestamp* timestamp_;
    ::uint64_t bufsize_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NetworkData

// string ip = 1;
inline void NetworkData::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& NetworkData::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NetworkData::set_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.NetworkData.ip)
}
inline std::string* NetworkData::mutable_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:NetworkData.NetworkData.ip)
  return _s;
}
inline const std::string& NetworkData::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void NetworkData::_internal_set_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline std::string* NetworkData::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline std::string* NetworkData::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.NetworkData.ip)
  return _impl_.ip_.Release();
}
inline void NetworkData::set_allocated_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.ip_.IsDefault()) {
          _impl_.ip_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NetworkData.NetworkData.ip)
}

// string uuid = 2;
inline void NetworkData::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& NetworkData::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NetworkData::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.NetworkData.uuid)
}
inline std::string* NetworkData::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:NetworkData.NetworkData.uuid)
  return _s;
}
inline const std::string& NetworkData::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void NetworkData::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* NetworkData::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* NetworkData::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.NetworkData.uuid)
  return _impl_.uuid_.Release();
}
inline void NetworkData::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uuid_.IsDefault()) {
          _impl_.uuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NetworkData.NetworkData.uuid)
}

// .NetworkData.ENetworkType type = 3;
inline void NetworkData::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::NetworkData::ENetworkType NetworkData::type() const {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.type)
  return _internal_type();
}
inline void NetworkData::set_type(::NetworkData::ENetworkType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:NetworkData.NetworkData.type)
}
inline ::NetworkData::ENetworkType NetworkData::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::NetworkData::ENetworkType>(_impl_.type_);
}
inline void NetworkData::_internal_set_type(::NetworkData::ENetworkType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint64 bufSize = 4;
inline void NetworkData::clear_bufsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bufsize_ = ::uint64_t{0u};
}
inline ::uint64_t NetworkData::bufsize() const {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.bufSize)
  return _internal_bufsize();
}
inline void NetworkData::set_bufsize(::uint64_t value) {
  _internal_set_bufsize(value);
  // @@protoc_insertion_point(field_set:NetworkData.NetworkData.bufSize)
}
inline ::uint64_t NetworkData::_internal_bufsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bufsize_;
}
inline void NetworkData::_internal_set_bufsize(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bufsize_ = value;
}

// string data = 5;
inline void NetworkData::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& NetworkData::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NetworkData::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.NetworkData.data)
}
inline std::string* NetworkData::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:NetworkData.NetworkData.data)
  return _s;
}
inline const std::string& NetworkData::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void NetworkData::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* NetworkData::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* NetworkData::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.NetworkData.data)
  return _impl_.data_.Release();
}
inline void NetworkData::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NetworkData.NetworkData.data)
}

// .google.protobuf.Timestamp timestamp = 6;
inline bool NetworkData::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& NetworkData::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& NetworkData::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.NetworkData.timestamp)
  return _internal_timestamp();
}
inline void NetworkData::unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkData.NetworkData.timestamp)
}
inline ::google::protobuf::Timestamp* NetworkData::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Timestamp* NetworkData::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.NetworkData.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* NetworkData::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* NetworkData::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:NetworkData.NetworkData.timestamp)
  return _msg;
}
inline void NetworkData::set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:NetworkData.NetworkData.timestamp)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NetworkData


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::NetworkData::ENetworkType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NetworkData::ENetworkType>() {
  return ::NetworkData::ENetworkType_descriptor();
}
template <>
struct is_proto_enum<::NetworkData::ELoginError> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NetworkData::ELoginError>() {
  return ::NetworkData::ELoginError_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_NetworkData_2eproto_2epb_2eh
