// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkData.proto
// Protobuf C++ Version: 5.28.3

#include "NetworkData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NetworkData {

inline constexpr NetworkData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{nullptr},
        bufsize_{::uint64_t{0u}},
        type_{static_cast< ::NetworkData::ENetworkType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR NetworkData::NetworkData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NetworkDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetworkDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetworkDataDefaultTypeInternal() {}
  union {
    NetworkData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetworkDataDefaultTypeInternal _NetworkData_default_instance_;
}  // namespace NetworkData
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_NetworkData_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_NetworkData_2eproto = nullptr;
const ::uint32_t
    TableStruct_NetworkData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.bufsize_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::NetworkData::NetworkData, _impl_.timestamp_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::NetworkData::NetworkData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NetworkData::_NetworkData_default_instance_._instance,
};
const char descriptor_table_protodef_NetworkData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021NetworkData.proto\022\013NetworkData\032\037google"
    "/protobuf/timestamp.proto\"\236\001\n\013NetworkDat"
    "a\022\n\n\002ip\030\001 \001(\t\022\014\n\004uuid\030\002 \001(\t\022\'\n\004type\030\003 \001("
    "\0162\031.NetworkData.ENetworkType\022\017\n\007bufSize\030"
    "\004 \001(\004\022\014\n\004data\030\005 \001(\t\022-\n\ttimestamp\030\006 \001(\0132\032"
    ".google.protobuf.Timestamp*\216\003\n\014ENetworkT"
    "ype\022\t\n\005LOGIN\020\000\022\014\n\010REGISTER\020\001\022\014\n\010RETRIEVE"
    "\020\002\022\n\n\006ACCESS\020\003\022\n\n\006REJECT\020\004\022\n\n\006LOGOUT\020\005\022\027"
    "\n\023COUNT_FOR_USER_DATA\020\006\022\010\n\004MOVE\020d\022\n\n\006ATT"
    "ACK\020e\022\r\n\tDROP_ITEM\020f\022\014\n\010USE_ITEM\020g\022\r\n\tUS"
    "E_SKILL\020h\022\030\n\024COUNT_FOR_LOGIC_DATA\020i\022\024\n\017S"
    "YSTEM_OPTION_1\020\310\001\022\024\n\017SYSTEM_OPTION_2\020\311\001\022"
    "\024\n\017SYSTEM_OPTION_3\020\312\001\022\032\n\025COUNT_FOR_SYSTE"
    "M_DATA\020\313\001\022\025\n\020ADMIN_SERVER_OFF\020\204\007\022\024\n\017ADMI"
    "N_SERVER_ON\020\205\007\022\030\n\023ADMIN_SERVER_REBOOT\020\206\007"
    "\022\031\n\024COUNT_FOR_ADMIN_DATA\020\207\007*H\n\013ELoginErr"
    "or\022\022\n\016USER_NOT_FOUND\020\000\022\026\n\022USER_ALREADY_E"
    "XIST\020\001\022\r\n\tINCORRECT\020\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_NetworkData_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_NetworkData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NetworkData_2eproto = {
    false,
    false,
    709,
    descriptor_table_protodef_NetworkData_2eproto,
    "NetworkData.proto",
    &descriptor_table_NetworkData_2eproto_once,
    descriptor_table_NetworkData_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_NetworkData_2eproto::offsets,
    file_level_enum_descriptors_NetworkData_2eproto,
    file_level_service_descriptors_NetworkData_2eproto,
};
namespace NetworkData {
const ::google::protobuf::EnumDescriptor* ENetworkType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_NetworkData_2eproto);
  return file_level_enum_descriptors_NetworkData_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENetworkType_internal_data_[] = {
    458752u, 262368u, 0u, 0u, 3758096384u, 7u, 0u, 0u, 30u, 902u, 901u, 903u, 900u, };
bool ENetworkType_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENetworkType_internal_data_);
}
const ::google::protobuf::EnumDescriptor* ELoginError_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_NetworkData_2eproto);
  return file_level_enum_descriptors_NetworkData_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ELoginError_internal_data_[] = {
    196608u, 0u, };
bool ELoginError_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class NetworkData::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NetworkData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetworkData, _impl_._has_bits_);
};

void NetworkData::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
NetworkData::NetworkData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NetworkData.NetworkData)
}
inline PROTOBUF_NDEBUG_INLINE NetworkData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NetworkData::NetworkData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_(arena, from.ip_),
        uuid_(arena, from.uuid_),
        data_(arena, from.data_) {}

NetworkData::NetworkData(
    ::google::protobuf::Arena* arena,
    const NetworkData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetworkData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.timestamp_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, bufsize_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, bufsize_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, bufsize_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:NetworkData.NetworkData)
}
inline PROTOBUF_NDEBUG_INLINE NetworkData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        ip_(arena),
        uuid_(arena),
        data_(arena) {}

inline void NetworkData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::type_));
}
NetworkData::~NetworkData() {
  // @@protoc_insertion_point(destructor:NetworkData.NetworkData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NetworkData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.ip_.Destroy();
  _impl_.uuid_.Destroy();
  _impl_.data_.Destroy();
  delete _impl_.timestamp_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    NetworkData::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_NetworkData_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &NetworkData::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<NetworkData>(),
            ::google::protobuf::Message::GetNewImpl<NetworkData>(),
            ::google::protobuf::Message::GetClearImpl<NetworkData>(), &NetworkData::ByteSizeLong,
                &NetworkData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(NetworkData, _impl_._cached_size_),
            false,
        },
        &NetworkData::kDescriptorMethods,
        &descriptor_table_NetworkData_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* NetworkData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 42, 2> NetworkData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NetworkData, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NetworkData::NetworkData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.ip_)}},
    // string uuid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.uuid_)}},
    // .NetworkData.ENetworkType type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetworkData, _impl_.type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.type_)}},
    // uint64 bufSize = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NetworkData, _impl_.bufsize_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.bufsize_)}},
    // string data = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.data_)}},
    // .google.protobuf.Timestamp timestamp = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.timestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.ip_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string uuid = 2;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.uuid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .NetworkData.ENetworkType type = 3;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint64 bufSize = 4;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.bufsize_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string data = 5;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.data_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Timestamp timestamp = 6;
    {PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
    "\27\2\4\0\0\4\0\0"
    "NetworkData.NetworkData"
    "ip"
    "uuid"
    "data"
  }},
};

PROTOBUF_NOINLINE void NetworkData::Clear() {
// @@protoc_insertion_point(message_clear_start:NetworkData.NetworkData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  _impl_.uuid_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.timestamp_ != nullptr);
    _impl_.timestamp_->Clear();
  }
  ::memset(&_impl_.bufsize_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.bufsize_)) + sizeof(_impl_.type_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NetworkData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NetworkData& this_ = static_cast<const NetworkData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NetworkData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NetworkData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NetworkData.NetworkData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string ip = 1;
          if (!this_._internal_ip().empty()) {
            const std::string& _s = this_._internal_ip();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NetworkData.NetworkData.ip");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string uuid = 2;
          if (!this_._internal_uuid().empty()) {
            const std::string& _s = this_._internal_uuid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NetworkData.NetworkData.uuid");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // .NetworkData.ENetworkType type = 3;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_type(), target);
          }

          // uint64 bufSize = 4;
          if (this_._internal_bufsize() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_bufsize(), target);
          }

          // string data = 5;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NetworkData.NetworkData.data");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Timestamp timestamp = 6;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NetworkData.NetworkData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NetworkData::ByteSizeLong(const MessageLite& base) {
          const NetworkData& this_ = static_cast<const NetworkData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NetworkData::ByteSizeLong() const {
          const NetworkData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NetworkData.NetworkData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string ip = 1;
            if (!this_._internal_ip().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_ip());
            }
            // string uuid = 2;
            if (!this_._internal_uuid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uuid());
            }
            // string data = 5;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data());
            }
          }
           {
            // .google.protobuf.Timestamp timestamp = 6;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
            }
          }
           {
            // uint64 bufSize = 4;
            if (this_._internal_bufsize() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_bufsize());
            }
            // .NetworkData.ENetworkType type = 3;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NetworkData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NetworkData*>(&to_msg);
  auto& from = static_cast<const NetworkData&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NetworkData.NetworkData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
    if (_this->_impl_.timestamp_ == nullptr) {
      _this->_impl_.timestamp_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_);
    } else {
      _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
    }
  }
  if (from._internal_bufsize() != 0) {
    _this->_impl_.bufsize_ = from._impl_.bufsize_;
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NetworkData::CopyFrom(const NetworkData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NetworkData.NetworkData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetworkData::InternalSwap(NetworkData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.type_)
      + sizeof(NetworkData::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(NetworkData, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata NetworkData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NetworkData
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_NetworkData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
