// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkData.proto
// Protobuf C++ Version: 5.29.3

#ifndef NetworkData_2eproto_2epb_2eh
#define NetworkData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_NetworkData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_NetworkData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_NetworkData_2eproto;
namespace NetworkData {
class LoginData;
struct LoginDataDefaultTypeInternal;
extern LoginDataDefaultTypeInternal _LoginData_default_instance_;
class PositionData;
struct PositionDataDefaultTypeInternal;
extern PositionDataDefaultTypeInternal _PositionData_default_instance_;
class RegisterData;
struct RegisterDataDefaultTypeInternal;
extern RegisterDataDefaultTypeInternal _RegisterData_default_instance_;
class RpcPacket;
struct RpcPacketDefaultTypeInternal;
extern RpcPacketDefaultTypeInternal _RpcPacket_default_instance_;
}  // namespace NetworkData
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NetworkData {
enum RpcMethod : int {
  NONE = 0,
  LOGIN = 1,
  REGISTER = 2,
  RETRIEVE = 3,
  ACCESS = 4,
  REJECT = 5,
  LOGOUT = 6,
  IN_GAME_NONE = 100,
  MOVE = 101,
  ATTACK = 102,
  DROP_ITEM = 103,
  USE_ITEM = 104,
  USE_SKILL = 105,
  STATE_NONE = 200,
  STATE_MOVE_START = 201,
  STATE_MOVE_END = 202,
  STATE_ATTACK_START = 203,
  STATE_ATTACK_END = 204,
  NETWORK_NONE = 500,
  UDP_PORT = 501,
  UUID = 502,
  PING = 503,
  PONG = 504,
  PACKET_COUNT = 505,
  RpcMethod_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RpcMethod_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RpcMethod_IsValid(int value);
extern const uint32_t RpcMethod_internal_data_[];
constexpr RpcMethod RpcMethod_MIN = static_cast<RpcMethod>(0);
constexpr RpcMethod RpcMethod_MAX = static_cast<RpcMethod>(505);
constexpr int RpcMethod_ARRAYSIZE = 505 + 1;
const ::google::protobuf::EnumDescriptor*
RpcMethod_descriptor();
template <typename T>
const std::string& RpcMethod_Name(T value) {
  static_assert(std::is_same<T, RpcMethod>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RpcMethod_Name().");
  return ::google::protobuf::internal::NameOfEnum(RpcMethod_descriptor(), value);
}
inline bool RpcMethod_Parse(absl::string_view name, RpcMethod* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RpcMethod>(
      RpcMethod_descriptor(), name, value);
}
enum ELoginError : int {
  USER_NOT_FOUND = 0,
  USER_ALREADY_EXIST = 1,
  INCORRECT = 2,
  ELoginError_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ELoginError_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ELoginError_IsValid(int value);
extern const uint32_t ELoginError_internal_data_[];
constexpr ELoginError ELoginError_MIN = static_cast<ELoginError>(0);
constexpr ELoginError ELoginError_MAX = static_cast<ELoginError>(2);
constexpr int ELoginError_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ELoginError_descriptor();
template <typename T>
const std::string& ELoginError_Name(T value) {
  static_assert(std::is_same<T, ELoginError>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ELoginError_Name().");
  return ELoginError_Name(static_cast<ELoginError>(value));
}
template <>
inline const std::string& ELoginError_Name(ELoginError value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ELoginError_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ELoginError_Parse(absl::string_view name, ELoginError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ELoginError>(
      ELoginError_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RegisterData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetworkData.RegisterData) */ {
 public:
  inline RegisterData() : RegisterData(nullptr) {}
  ~RegisterData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RegisterData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RegisterData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RegisterData(
      ::google::protobuf::internal::ConstantInitialized);

  inline RegisterData(const RegisterData& from) : RegisterData(nullptr, from) {}
  inline RegisterData(RegisterData&& from) noexcept
      : RegisterData(nullptr, std::move(from)) {}
  inline RegisterData& operator=(const RegisterData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterData& operator=(RegisterData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegisterData& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegisterData* internal_default_instance() {
    return reinterpret_cast<const RegisterData*>(
        &_RegisterData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RegisterData& a, RegisterData& b) { a.Swap(&b); }
  inline void Swap(RegisterData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegisterData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RegisterData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RegisterData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RegisterData& from) { RegisterData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RegisterData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NetworkData.RegisterData"; }

 protected:
  explicit RegisterData(::google::protobuf::Arena* arena);
  RegisterData(::google::protobuf::Arena* arena, const RegisterData& from);
  RegisterData(::google::protobuf::Arena* arena, RegisterData&& from) noexcept
      : RegisterData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username() ;
  const std::string& username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* value);

  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(
      const std::string& value);
  std::string* _internal_mutable_username();

  public:
  // string password = 2;
  void clear_password() ;
  const std::string& password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* value);

  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(
      const std::string& value);
  std::string* _internal_mutable_password();

  public:
  // @@protoc_insertion_point(class_scope:NetworkData.RegisterData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      49, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RegisterData& from_msg);
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkData_2eproto;
};
// -------------------------------------------------------------------

class PositionData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetworkData.PositionData) */ {
 public:
  inline PositionData() : PositionData(nullptr) {}
  ~PositionData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PositionData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PositionData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PositionData(
      ::google::protobuf::internal::ConstantInitialized);

  inline PositionData(const PositionData& from) : PositionData(nullptr, from) {}
  inline PositionData(PositionData&& from) noexcept
      : PositionData(nullptr, std::move(from)) {}
  inline PositionData& operator=(const PositionData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionData& operator=(PositionData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PositionData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PositionData* internal_default_instance() {
    return reinterpret_cast<const PositionData*>(
        &_PositionData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PositionData& a, PositionData& b) { a.Swap(&b); }
  inline void Swap(PositionData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PositionData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PositionData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PositionData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PositionData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PositionData& from) { PositionData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PositionData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NetworkData.PositionData"; }

 protected:
  explicit PositionData(::google::protobuf::Arena* arena);
  PositionData(::google::protobuf::Arena* arena, const PositionData& from);
  PositionData(::google::protobuf::Arena* arena, PositionData&& from) noexcept
      : PositionData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kX1FieldNumber = 1,
    kY1FieldNumber = 2,
    kZ1FieldNumber = 3,
    kX2FieldNumber = 4,
    kY2FieldNumber = 5,
    kZ2FieldNumber = 6,
  };
  // float x1 = 1;
  void clear_x1() ;
  float x1() const;
  void set_x1(float value);

  private:
  float _internal_x1() const;
  void _internal_set_x1(float value);

  public:
  // float y1 = 2;
  void clear_y1() ;
  float y1() const;
  void set_y1(float value);

  private:
  float _internal_y1() const;
  void _internal_set_y1(float value);

  public:
  // float z1 = 3;
  void clear_z1() ;
  float z1() const;
  void set_z1(float value);

  private:
  float _internal_z1() const;
  void _internal_set_z1(float value);

  public:
  // float x2 = 4;
  void clear_x2() ;
  float x2() const;
  void set_x2(float value);

  private:
  float _internal_x2() const;
  void _internal_set_x2(float value);

  public:
  // float y2 = 5;
  void clear_y2() ;
  float y2() const;
  void set_y2(float value);

  private:
  float _internal_y2() const;
  void _internal_set_y2(float value);

  public:
  // float z2 = 6;
  void clear_z2() ;
  float z2() const;
  void set_z2(float value);

  private:
  float _internal_z2() const;
  void _internal_set_z2(float value);

  public:
  // @@protoc_insertion_point(class_scope:NetworkData.PositionData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PositionData& from_msg);
    float x1_;
    float y1_;
    float z1_;
    float x2_;
    float y2_;
    float z2_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkData_2eproto;
};
// -------------------------------------------------------------------

class LoginData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetworkData.LoginData) */ {
 public:
  inline LoginData() : LoginData(nullptr) {}
  ~LoginData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LoginData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LoginData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LoginData(
      ::google::protobuf::internal::ConstantInitialized);

  inline LoginData(const LoginData& from) : LoginData(nullptr, from) {}
  inline LoginData(LoginData&& from) noexcept
      : LoginData(nullptr, std::move(from)) {}
  inline LoginData& operator=(const LoginData& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginData& operator=(LoginData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginData& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginData* internal_default_instance() {
    return reinterpret_cast<const LoginData*>(
        &_LoginData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LoginData& a, LoginData& b) { a.Swap(&b); }
  inline void Swap(LoginData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LoginData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LoginData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LoginData& from) { LoginData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LoginData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NetworkData.LoginData"; }

 protected:
  explicit LoginData(::google::protobuf::Arena* arena);
  LoginData(::google::protobuf::Arena* arena, const LoginData& from);
  LoginData(::google::protobuf::Arena* arena, LoginData&& from) noexcept
      : LoginData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username() ;
  const std::string& username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* value);

  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(
      const std::string& value);
  std::string* _internal_mutable_username();

  public:
  // string password = 2;
  void clear_password() ;
  const std::string& password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* value);

  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(
      const std::string& value);
  std::string* _internal_mutable_password();

  public:
  // @@protoc_insertion_point(class_scope:NetworkData.LoginData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      46, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LoginData& from_msg);
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkData_2eproto;
};
// -------------------------------------------------------------------

class RpcPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetworkData.RpcPacket) */ {
 public:
  inline RpcPacket() : RpcPacket(nullptr) {}
  ~RpcPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RpcPacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RpcPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RpcPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline RpcPacket(const RpcPacket& from) : RpcPacket(nullptr, from) {}
  inline RpcPacket(RpcPacket&& from) noexcept
      : RpcPacket(nullptr, std::move(from)) {}
  inline RpcPacket& operator=(const RpcPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcPacket& operator=(RpcPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const RpcPacket* internal_default_instance() {
    return reinterpret_cast<const RpcPacket*>(
        &_RpcPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RpcPacket& a, RpcPacket& b) { a.Swap(&b); }
  inline void Swap(RpcPacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcPacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RpcPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RpcPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RpcPacket& from) { RpcPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RpcPacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NetworkData.RpcPacket"; }

 protected:
  explicit RpcPacket(::google::protobuf::Arena* arena);
  RpcPacket(::google::protobuf::Arena* arena, const RpcPacket& from);
  RpcPacket(::google::protobuf::Arena* arena, RpcPacket&& from) noexcept
      : RpcPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kDataFieldNumber = 3,
    kTimestampFieldNumber = 4,
    kMethodFieldNumber = 2,
  };
  // bytes uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // bytes data = 3;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .google.protobuf.Timestamp timestamp = 4;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* _internal_mutable_timestamp();

  public:
  // .NetworkData.RpcMethod method = 2;
  void clear_method() ;
  ::NetworkData::RpcMethod method() const;
  void set_method(::NetworkData::RpcMethod value);

  private:
  ::NetworkData::RpcMethod _internal_method() const;
  void _internal_set_method(::NetworkData::RpcMethod value);

  public:
  // @@protoc_insertion_point(class_scope:NetworkData.RpcPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RpcPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::Timestamp* timestamp_;
    int method_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LoginData

// string username = 1;
inline void LoginData::clear_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.ClearToEmpty();
}
inline const std::string& LoginData::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.LoginData.username)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LoginData::set_username(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.LoginData.username)
}
inline std::string* LoginData::mutable_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:NetworkData.LoginData.username)
  return _s;
}
inline const std::string& LoginData::_internal_username() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.username_.Get();
}
inline void LoginData::_internal_set_username(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.Set(value, GetArena());
}
inline std::string* LoginData::_internal_mutable_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.username_.Mutable( GetArena());
}
inline std::string* LoginData::release_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.LoginData.username)
  return _impl_.username_.Release();
}
inline void LoginData::set_allocated_username(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.LoginData.username)
}

// string password = 2;
inline void LoginData::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
}
inline const std::string& LoginData::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.LoginData.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LoginData::set_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.LoginData.password)
}
inline std::string* LoginData::mutable_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:NetworkData.LoginData.password)
  return _s;
}
inline const std::string& LoginData::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void LoginData::_internal_set_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline std::string* LoginData::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline std::string* LoginData::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.LoginData.password)
  return _impl_.password_.Release();
}
inline void LoginData::set_allocated_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.LoginData.password)
}

// -------------------------------------------------------------------

// RegisterData

// string username = 1;
inline void RegisterData::clear_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.ClearToEmpty();
}
inline const std::string& RegisterData::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.RegisterData.username)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RegisterData::set_username(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.RegisterData.username)
}
inline std::string* RegisterData::mutable_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:NetworkData.RegisterData.username)
  return _s;
}
inline const std::string& RegisterData::_internal_username() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.username_.Get();
}
inline void RegisterData::_internal_set_username(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.Set(value, GetArena());
}
inline std::string* RegisterData::_internal_mutable_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.username_.Mutable( GetArena());
}
inline std::string* RegisterData::release_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.RegisterData.username)
  return _impl_.username_.Release();
}
inline void RegisterData::set_allocated_username(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.RegisterData.username)
}

// string password = 2;
inline void RegisterData::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
}
inline const std::string& RegisterData::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.RegisterData.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RegisterData::set_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.RegisterData.password)
}
inline std::string* RegisterData::mutable_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:NetworkData.RegisterData.password)
  return _s;
}
inline const std::string& RegisterData::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void RegisterData::_internal_set_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline std::string* RegisterData::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline std::string* RegisterData::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.RegisterData.password)
  return _impl_.password_.Release();
}
inline void RegisterData::set_allocated_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.RegisterData.password)
}

// -------------------------------------------------------------------

// PositionData

// float x1 = 1;
inline void PositionData::clear_x1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x1_ = 0;
}
inline float PositionData::x1() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.x1)
  return _internal_x1();
}
inline void PositionData::set_x1(float value) {
  _internal_set_x1(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.x1)
}
inline float PositionData::_internal_x1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x1_;
}
inline void PositionData::_internal_set_x1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x1_ = value;
}

// float y1 = 2;
inline void PositionData::clear_y1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y1_ = 0;
}
inline float PositionData::y1() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.y1)
  return _internal_y1();
}
inline void PositionData::set_y1(float value) {
  _internal_set_y1(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.y1)
}
inline float PositionData::_internal_y1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y1_;
}
inline void PositionData::_internal_set_y1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y1_ = value;
}

// float z1 = 3;
inline void PositionData::clear_z1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z1_ = 0;
}
inline float PositionData::z1() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.z1)
  return _internal_z1();
}
inline void PositionData::set_z1(float value) {
  _internal_set_z1(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.z1)
}
inline float PositionData::_internal_z1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z1_;
}
inline void PositionData::_internal_set_z1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z1_ = value;
}

// float x2 = 4;
inline void PositionData::clear_x2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x2_ = 0;
}
inline float PositionData::x2() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.x2)
  return _internal_x2();
}
inline void PositionData::set_x2(float value) {
  _internal_set_x2(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.x2)
}
inline float PositionData::_internal_x2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x2_;
}
inline void PositionData::_internal_set_x2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x2_ = value;
}

// float y2 = 5;
inline void PositionData::clear_y2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y2_ = 0;
}
inline float PositionData::y2() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.y2)
  return _internal_y2();
}
inline void PositionData::set_y2(float value) {
  _internal_set_y2(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.y2)
}
inline float PositionData::_internal_y2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y2_;
}
inline void PositionData::_internal_set_y2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y2_ = value;
}

// float z2 = 6;
inline void PositionData::clear_z2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z2_ = 0;
}
inline float PositionData::z2() const {
  // @@protoc_insertion_point(field_get:NetworkData.PositionData.z2)
  return _internal_z2();
}
inline void PositionData::set_z2(float value) {
  _internal_set_z2(value);
  // @@protoc_insertion_point(field_set:NetworkData.PositionData.z2)
}
inline float PositionData::_internal_z2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z2_;
}
inline void PositionData::_internal_set_z2(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z2_ = value;
}

// -------------------------------------------------------------------

// RpcPacket

// bytes uuid = 1;
inline void RpcPacket::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& RpcPacket::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.RpcPacket.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RpcPacket::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.RpcPacket.uuid)
}
inline std::string* RpcPacket::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:NetworkData.RpcPacket.uuid)
  return _s;
}
inline const std::string& RpcPacket::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void RpcPacket::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* RpcPacket::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* RpcPacket::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.RpcPacket.uuid)
  return _impl_.uuid_.Release();
}
inline void RpcPacket::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.RpcPacket.uuid)
}

// .NetworkData.RpcMethod method = 2;
inline void RpcPacket::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
}
inline ::NetworkData::RpcMethod RpcPacket::method() const {
  // @@protoc_insertion_point(field_get:NetworkData.RpcPacket.method)
  return _internal_method();
}
inline void RpcPacket::set_method(::NetworkData::RpcMethod value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:NetworkData.RpcPacket.method)
}
inline ::NetworkData::RpcMethod RpcPacket::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::NetworkData::RpcMethod>(_impl_.method_);
}
inline void RpcPacket::_internal_set_method(::NetworkData::RpcMethod value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// bytes data = 3;
inline void RpcPacket::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& RpcPacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.RpcPacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RpcPacket::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NetworkData.RpcPacket.data)
}
inline std::string* RpcPacket::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:NetworkData.RpcPacket.data)
  return _s;
}
inline const std::string& RpcPacket::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void RpcPacket::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* RpcPacket::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* RpcPacket::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.RpcPacket.data)
  return _impl_.data_.Release();
}
inline void RpcPacket::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NetworkData.RpcPacket.data)
}

// .google.protobuf.Timestamp timestamp = 4;
inline bool RpcPacket::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& RpcPacket::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& RpcPacket::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NetworkData.RpcPacket.timestamp)
  return _internal_timestamp();
}
inline void RpcPacket::unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkData.RpcPacket.timestamp)
}
inline ::google::protobuf::Timestamp* RpcPacket::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* RpcPacket::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NetworkData.RpcPacket.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* RpcPacket::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* RpcPacket::mutable_timestamp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:NetworkData.RpcPacket.timestamp)
  return _msg;
}
inline void RpcPacket::set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:NetworkData.RpcPacket.timestamp)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NetworkData


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::NetworkData::RpcMethod> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NetworkData::RpcMethod>() {
  return ::NetworkData::RpcMethod_descriptor();
}
template <>
struct is_proto_enum<::NetworkData::ELoginError> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NetworkData::ELoginError>() {
  return ::NetworkData::ELoginError_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // NetworkData_2eproto_2epb_2eh
